### PR TITLE
Add blade template section for theme contributors

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @mwilliams2014, I'm sending you a draft update with the tutorial to use the new blade template for theme contributors. Please, start reviewing it, but hold off the final publication until Blade 2.0 has been released. @gamerson mentioned this should be happening around next Friday.

/cc @codyhoag, @sez11a

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Hey @jbalsas . Thanks for sending this to us! Since this is @codyhoag 's area, he is going to review these docs for you, so they can best match the rest of the blade template docs. thx!

**Comment by jbalsas** [comment]
Perfect, thanks a lot, @mwilliams2014!

Should I resend to Cody, then?

**Comment by mwilliams2014** [comment]
@jbalsas @codyhoag can just pull from this pr. thx!

**Comment by codyhoag** [comment]
@jbalsas thanks for writing this up for the theme contributor template. I've been working on Blade 2.0 updates in a separate branch, so I'll merge your content into that branch.

I have the latest Blade 2.0 version installed, but I don't see the theme contributor template. Will this be available in the next Blade 2.0 release on https://liferay-test-01.ci.cloudbees.com/job/liferay-blade-cli/ ?

**Comment by jbalsas** [comment]
Hey @codyhoag!

Yeah, the [theme contributuor blade template](https://github.com/liferay/liferay-portal/tree/master/modules/sdk/project-templates-theme-contributor) was merged last week. I talked to @gamerson, and the goal is to have this one and the `SoyPortlet` blade template that @brunobasto is working on in the upcoming 2.0 release.

Please, sync with Greg to get the most up-to-date news.

Thanks!

**Comment by codyhoag** [comment]
Thanks @jbalsas. Sounds good!

I've merged this into my local branch 😃

**Comment by jbalsas** [comment]
Thanks a lot @codyhoag!

**Pull request closed without merging**
