### PR TITLE
LRDOCS-3167 Create AlloyEditor section and add tutorial to create new buttons

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by codyhoag** [comment]
Hey @jbalsas; would you consider this new tutorial on creating/contributing AlloyEditor buttons to be complimentary to our existing tutorials [here](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-0/wysiwyg-editors)? Just want to make sure we don't have too much overlap between the articles. 😃 

From what I can tell, this tutorial goes into creating and contributing a specific editor's button, whereas the existing ones are more high level explaining injecting configs/buttons to WYSIWYG editors in general. Is that correct?

**Comment by jbalsas** [comment]
That is correct, @codyhoag. This is complimentary, since none of those really cover how to actually create or contribute a button.

We might make some of it more general later, but we need to at least get it out now.

**Comment by codyhoag** [comment]
Sounds good. Thanks @jbalsas

**Comment by mwilliams2014** [comment]
merged locally. thx!

**Comment by mwilliams2014** [comment]
sent https://github.com/sez11a/liferay-docs/pull/1986

**Pull request closed without merging**
