### PR TITLE
LRDOCS-3108 Add tutorial for upgrade sharding

### PR DESCRIPTION
**Pull request by mdelapenya**
Hi Michael, this is the first draft for the sharding upgrade tutorial. @achaparro told me that we need to inform users with sharding how to upgrade to Liferay 7. Thank you buddy\!

### CODE REVIEW

**Comment by achaparro** [comment]
Hey @mwilliams2014,

Did you have the chance to review this? Actually there is no official documentation about how to upgrade sharding environments and customers and CE users will need it.

Thanks!

**Comment by mwilliams2014** [comment]
Hey @achaparro,

I'll review it this week. I apologize for the delay. We published a lot of front-end docs last week, so it has been kind of hectic.

**Comment by sez11a** [comment]
Hey @achaparro it seems this was sent to the wrong person. Can you send this one to me? Thanks!

**Comment by mdelapenya** [comment]
Sent to @sez11a here: https://github.com/sez11a/liferay-docs/pull/2010

Thanks!

**Pull request closed without merging**
