### PR TITLE
LRDOCS-5947 migrate latest liferay-npm-bundler wiki updates

### PR DESCRIPTION
**Pull request by mwilliams2014**
cc @izaera here are the latest doc updates for the liferay-npm-bundler. I have sent you some more questions I had on slack. Everything should be good. If you could mainly review Creating and Bundling JavaScript Portlets with JavaScript Tooling to make sure everything looks good. Feel free to review the rest if you want, but it's primarily a port of the wiki updates. Thanks!

Note: we now have a 7.1.x branch in the liferay-docs repo. Master is now 7.2 docs. (that's why this PR is addressed to myself :-))

### CODE REVIEW

**Comment by izaera** [comment]
Oops. I just updated the wiki (again) yesterday to reflect the project's name change.

Now: 
* `liferay-npm-build-tools` is `liferay-js-toolkit`
* `Liferay Bundle Generator` is `Liferay JS Generator`
* `export bundle`/`Shared packages bundle` becomes `shared bundle` (see [before](https://github.com/liferay/liferay-js-toolkit/blob/master/packages/generator-liferay-bundle/src/target-export-bundle/target-description.json#L2) and [now](https://github.com/liferay/liferay-js-toolkit/blob/develop/packages/generator-liferay-js/src/target-shared-bundle/target-description.json#L2))

I can send you the diffs for the wiki if you think they may be useful to see what has changed...

**Comment by izaera** [comment]
Hope that helps tracking the latest changes :pray: .

**Comment by mwilliams2014** [comment]
You just caught me in time I think. I sent the 7.1 updates yesterday: https://github.com/sez11a/liferay-docs/pull/4187

**Comment by mwilliams2014** [comment]
@izaera , so now we have the Liferay JS Theme Toolkit, the Liferay JS Toolkit and the Liferay JS Generator

**Comment by izaera** [comment]
@mwilliams2014 Yes. That was the idea: standardizing the names of every tool.

**Pull request merged**
